#!/bin/bash
#
# Setup files for using WP CLI from host machine.
# See https://github.com/salcode/ssh-into-local-by-flywheel/issues/5

yml_path=$(pwd)/wp-cli.local.yml;
php_path=$(pwd)/wp-cli.local.php;

if [ -f $yml_path ]; then
    echo "Aborting: wp-cli.local.yml already exists"
	exit 1;
fi

if [ -f $php_path ]; then
    echo "Aborting: wp-cli.local.php already exists"
	exit 1;
fi

printf "Database host [192.168.94.100]: "
read -r host
host=${host:-192.168.94.100}
echo

printf "Database port [4002]: "
read -r port
port=${port:-4002}
echo

echo "Creating ${yml_path}"
echo
cat >${yml_path} <<EOL
path: app/public
require:
  - wp-cli.local.php
EOL

echo "Creating ${php_path}"
echo
cat >${php_path} <<EOL
<?php
define('DB_HOST', '${host}:${port}');
define('DB_USER', 'root');
define('DB_PASSWORD', 'root');

error_reporting(0);
@ini_set('display_errors', 0);
define( 'WP_DEBUG', false );
EOL

siteurl=`wp option get siteurl 2> /dev/null`

if [ $? -ne 0 ]
then
  echo "Could not connect, please re-check your database settings."
  exit 1
fi

echo "Successfully connected to ${siteurl}"
exit 0
